apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack
  namespace: prodlab
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: bookstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack
  namespace: prodlab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: bookstack
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: prodlab
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: linuxserver/bookstack
        env:
        - name: "APP_URL"
          value: "https://wiki.k8s.array21.dev"
        - name: "DB_HOST"
          value: "mariadb.intern.array21.dev"
        - name: "DB_DATABASE"
          value: prod_bookstack_v2
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: username
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: password
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - name: web
          containerPort: 80
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bookstack
---
apiVersion: v1
kind: Service
metadata:
  name: bookstack
  namespace: prodlab
spec:
  selector:
    app: bookstack
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstack
  namespace: prodlab
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-array21"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - wiki.k8s.array21.dev
    secretName: wiki-k8s-array21-dev
  rules:
  - host: wiki.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookstack
            port:
              number: 80
