apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
  namespace: prodlab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: prodlab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: gitea
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: prodlab
  labels:
    app.kubernetes.io/name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
    spec:
      automountServiceAccountToken: false
      containers:
      - name: gitea
        image: gitea/gitea:1.14.4
        securityContext:
          capabilities:
            drop:
            - CAP_NET_RAW
        env:
        - name: 'USER_UID'
          value: '1000'
        - name: 'USER_GID'
          value: '1000'
        - name: 'GITEA__database__DB_TYPE'
          value: 'mysql'
        - name: 'GITEA__database__HOST'
          value: 'mariadb.intern.array21.dev'
        - name: 'GITEA__database__NAME'
          value: 'gitea'
        - name: 'GITEA__database__USER'
          valueFrom:
            secretKeyRef:
              name: gitea
              key: user
        - name: 'GITEA__database__PASSWD'
          valueFrom:
            secretKeyRef:
              name: gitea
              key: passwd
        ports:
        - name: web
          containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: prodlab
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gitea
  ports:
  - protocol: TCP
    name: web
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: prodlab
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-array21"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - gitea.k8s.array21.dev
    secretName: gitea-k8s-array21-dev
  rules:
  - host: gitea.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              number: 3000
