apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediastack-bazarr
  namespace: external-names
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-array21"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
spec:
  tls:
  - secretName: bazarr-apps-array21-dev
    hosts:
    - bazarr.apps.array21.dev
  rules:
  - host: bazarr.apps.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mediastack
            port:
              number: 6767