apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-server
  namespace: twinsight
  labels:
    app: content-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-server
  template:
    metadata:
      labels: 
        app: content-server
    spec:
      containers:
      - name: content-server
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/twinsight-content-server
        ports:
        - containerPort: 8080
          name: api
        env:
        - name: MYSQL_HOST
          value: mariadb.intern.array21.dev
        - name: MYSQL_DATABASE
          value: twinsight-prod-content-server
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: content-server-mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: content-server-mysql-password
        - name: LOGIN_SERVER_HOST
          value: https://login.api.twinsight.media
---
apiVersion: v1
kind: Service
metadata:
  name: content-server
  namespace: twinsight
spec:
  selector:
    app: content-server
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: content-server
  namespace: twinsight
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - hosts:
    - content.api.twinsight.media
    secretName: twinsight-media-tls
  rules:
  - host: content.api.twinsight.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: content-server
            port:
              number: 8080
