apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-server
  namespace: twinsight
  labels:
    app: location-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-server
  template:
    metadata:
      labels: 
        app: location-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: location-server
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/twinsight-location-server:0.1.0
        ports:
        - containerPort: 8080
          name: api
        env:
        - name: MYSQL_HOST
          value: mariadb.intern.array21.dev
        - name: MYSQL_DATABASE
          value: twinsight-prod-location-server
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: location-server
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-server
              key: mysql-password
        - name: LOGIN_SERVER_HOST
          value: http://login-server.twinsight.svc.cluster.local:8080
---
apiVersion: v1
kind: Service
metadata:
  name: location-server
  namespace: twinsight
spec:
  selector:
    app: location-server
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: location-server
  namespace: twinsight
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-twinsight-media"
spec:
  tls:
  - hosts:
    - location.api.twinsight.media
    secretName: location-api-twinsight-media
  rules:
  - host: location.api.twinsight.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: location-server
            port:
              number: 8080
