apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-server
  namespace: twinsight
  labels:
    app: login-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-server
  template:
    metadata:
      labels: 
        app: login-server
    spec:
      containers:
      - name: login-server
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/twinsight-login-server:latest
        ports:
        - containerPort: 8080
          name: api
        env:
        - name: MYSQL_HOST
          value: mariadb.intern.array21.dev
        - name: MYSQL_DATABASE
          value: twinsight-prod-login-server
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: login-server-mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: login-server-mysql-password
        - name: PASSWORD_PEPPER
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: login-server-password-pepper
---
apiVersion: v1
kind: Service
metadata:
  name: login-server
  namespace: twinsight
spec:
  selector:
    app: login-server
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-server
  namespace: twinsight
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - login.api.twinsight.media
    secretName: twinsight-media-tls
  rules:
  - host: login.api.twinsight.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-server
            port:
              number: 8080
