apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-data
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: bazarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: bazarr-data
  storageClassName: longhorn-static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-movies
  namespace: homelab
spec:
  capacity:
    storage: 2000G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage-pool/media/movies
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-movies
  namespace: homelab
spec:
  storageClassName: ""
  volumeName: bazarr-movies
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-tvshows
  namespace: homelab
spec:
  capacity:
    storage: 10000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/media/tvshows
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-tvshows
  namespace: homelab
spec:
  storageClassName: ""
  volumeName: bazarr-tvshows
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      automountServiceAccountToken: false
      containers:
      - name: bazarr
        image: linuxserver/bazarr
        ports:
        - containerPort: 6767
          name: webint
        volumeMounts:
        - name: data
          mountPath: /config
        - name: movies
          mountPath: /movies
        - name: tvshows
          mountPath: /tv
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bazarr-data
      - name: movies
        persistentVolumeClaim:
          claimName: bazarr-movies
      - name: tvshows
        persistentVolumeClaim: 
          claimName: bazarr-tvshows
---
apiVersion: v1
kind: Service
metadata:
  namespace: homelab
  name: bazarr
spec:
  selector:
    app.kubernetes.io/name: bazarr
  ports:
  - protocol: TCP
    name: webint
    port: 6767
    targetPort: 6767
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    cert-manager.io/cluster-issuer: letsencrypt-array21

spec:
  tls:
  - hosts:
    - bazarr.k8s.array21.dev
    secretName: bazarr-k8s-array21-dev
  rules:
  - host: bazarr.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767
