apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-data
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: jackett
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: jackett-data
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homelab
  name: jackett
  labels:
    app.kubernetes.io/name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: etc
        image: linuxserver/jackett:v0.18.925-ls47
        volumeMounts:
        - name: etc
          mountPath: /mnt/etc
        command: ["bash", "-c", "cp -r /etc/* /mnt/etc/"]
      - name: app
        image: linuxserver/jackett:v0.18.925-ls47
        volumeMounts:
        - name: app
          mountPath: /mnt/app
        command: ["bash", "-c", "cp -r /app/* /mnt/app/"]
      containers:
      - name: jackett
        image: linuxserver/jackett:v0.18.925-ls47
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - CAP_NET_RAW
        ports:
        - containerPort: 9117
        env:
        - name: COMPlus_EnableDiagnostics
          value: "0"
        volumeMounts:
        - name: data
          mountPath: /config
        - name: var-run-s6
          mountPath: /var/run/s6
        - name: etc
          mountPath: /etc
        - name: defaults
          mountPath: /defaults
        - name: app
          mountPath: /app
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jackett-data
      - name: var-run-s6
        emptyDir: {}
      - name: etc
        emptyDir: {}
      - name: defaults
        emptyDir: {}
      - name: app
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: homelab
  name: jackett
spec:
  selector:
    app.kubernetes.io/name: jackett
  ports:
  - protocol: TCP
    port: 9117
    targetPort: 9117
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    cert-manager.io/cluster-issuer: letsencrypt-array21
spec:
  tls:
  - hosts:
    - jackett.k8s.array21.dev
    secretName: jacket-k8s-array21-dev
  rules:
  - host: jackett.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett
            port:
              number: 9117
