apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-data
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: jackett
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: jackett-data
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homelab
  name: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      automountServiceAccountToken: false
      containers:
      - name: jackett
        image: linuxserver/jackett
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: data
          mountPath: /config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jackett-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: homelab
  name: jackett
spec:
  selector:
    app: jackett
  ports:
  - protocol: TCP
    port: 9117
    targetPort: 9117
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    cert-manager.io/cluster-issuer: letsencrypt-array21
spec:
  tls:
  - hosts:
    - jackett.k8s.array21.dev
    secretName: jacket-k8s-array21-dev
  rules:
  - host: jackett.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett
            port:
              number: 9117
