apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-data
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: lidarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: lidarr-data
  storageClassName: longhorn-static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-transmission
  namespace: homelab
spec:
  capacity:
    storage: 2000G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage-pool/transmission
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-transmission
  namespace: homelab
spec:
  volumeName: lidarr-transmission
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music
  namespace: homelab
spec:
  capacity:
    storage: 10000G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage-pool/media/music
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-music
  namespace: homelab
spec:
  volumeName: lidarr-music
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: homelab
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr
        ports:
        - containerPort: 8686
        volumeMounts:
        - name: data
          mountPath: /config
        - name: transmission
          mountPath: /data/completed/
        - name: music
          mountPath: /music
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lidarr-data
      - name: transmission
        persistentVolumeClaim:
          claimName: lidarr-transmission
      - name: music
        persistentVolumeClaim: 
          claimName: lidarr-music
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: homelab
spec:
  selector:
    app: lidarr
  ports:
  - protocol: TCP
    port: 8686
    targetPort: 8686
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    cert-manager.io/cluster-issuer: letsencrypt-array21

spec:
  tls:
  - hosts:
    - lidarr.k8s.array21.dev
    secretName: lidarr-k8s-array21-dev
  rules:
  - host: lidarr.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr
            port:
              number: 8686
