apiVersion: v1
kind: Secret
metadata:
  name: lidarr-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "bGlkYXJyCg=="
  node.session.auth.password: "UFI2WGMyWHpzQjNISHk4clIycTkK"
---
#lidarrs storage directory. iSCSI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.4:3260
    iqn: 'iqn.2021-05.intern.array21.dev:lidarr'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: lidarr-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
#Transmissions download directory. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-lidarr-storage
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/transmission
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
#Export Directory for lidarr. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-lidarr-storage
spec:
  capacity:
    storage: 10000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/media/music
    server: 192.168.2.3
  persistentVolumeReclaimPolicy: Retain
---
#lidarrs config directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
spec:
  volumeName: lidarr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
#Transmissions download directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-lidarr-storage
spec:
  volumeName: transmission-lidarr-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
#lidarrs export directory for TV Shows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-lidarr-storage
spec:
  volumeName: music-lidarr-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
#Deployment. lidarr container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr
        ports:
        #Webinterface
        - containerPort: 8686
          name: webint
        volumeMounts:
        #lidarrs config directory (iSCSI)
        - name: lidarr-config
          mountPath: /config
        #Transmission download directory
        - name: transmission-storage
          mountPath: /data/completed/
        #Final resting place for the downloaded media
        - name: music-storage
          mountPath: /music
      volumes:
      - name: lidarr-config
        persistentVolumeClaim:
          claimName: lidarr-config
      - name: transmission-storage
        persistentVolumeClaim:
          claimName: transmission-lidarr-storage
      - name: music-storage
        persistentVolumeClaim: 
          claimName: music-lidarr-storage
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  selector:
    app: lidarr
  ports:
  #Webinterface
  - protocol: TCP
    name: webint
    port: 8686
    targetPort: 8686
---
#Ingress resource. Picked up by the NGINX ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  annotations:
    kubernets.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 85.144.63.138,192.168.1.0/24
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - lidarr.k8s.array21.dev
    secretName: array21-tls
  rules:
  - host: lidarr.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr
            port:
              number: 8686
