apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-data
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: sonarr-data
  storageClassName: longhorn-static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-transmission
  namespace: homelab
spec:
  capacity:
    storage: 2000G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage-pool/transmission
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-transmission
  namespace: homelab
spec:
  volumeName: sonarr-transmission
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tvshows
  namespace: homelab
spec:
  capacity:
    storage: 10000G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage-pool/media/tvshows
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tvshows
  namespace: homelab
spec:
  volumeName: sonarr-tvshows
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: homelab
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: data
          mountPath: /config
        - name: transmission
          mountPath: /data/completed/
        - name: tvshows
          mountPath: /tv
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarr-data
      - name: transmission
        persistentVolumeClaim:
          claimName: sonarr-transmission
      - name: tvshows
        persistentVolumeClaim: 
          claimName: sonarr-tvshows
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: homelab
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/16
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    cert-manager.io/cluster-issuer: letsencrypt-array21

spec:
  tls:
  - hosts:
    - sonarr.k8s.array21.dev
    secretName: sonarr-k8s-array21-dev
  rules:
  - host: sonarr.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
