apiVersion: v1
kind: Secret
metadata:
  name: sonarr-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "c29uYXJyCg=="
  node.session.auth.password: "WlBIZUJLNDdybjVaRlhyOXkzakMK"
---
#Sonarrs storage directory. iSCSI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.4:3260
    iqn: 'iqn.2021-05.intern.array21.dev:sonarr'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: sonarr-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
#Transmissions download directory. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-sonarr-storage
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/transmission
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
#Export Directory for Sonarr. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshow-sonarr-storage
spec:
  capacity:
    storage: 10000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/media/tvshows
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
#Sonarrs config directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  volumeName: sonarr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
#Transmissions download directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-sonarr-storage
spec:
  volumeName: transmission-sonarr-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
#Sonarrs export directory for TV Shows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshow-sonarr-storage
spec:
  volumeName: tvshow-sonarr-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
#Deployment. Sonarr container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: 'linuxserver/sonarr:latest'
        ports:
        - containerPort: 8989
          name: webint
        volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: transmission-storage
          mountPath: /data/completed/
        - name: tvshow-storage
          mountPath: /tv
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: transmission-storage
        persistentVolumeClaim:
          claimName: transmission-sonarr-storage
      - name: tvshow-storage
        persistentVolumeClaim: 
          claimName: tvshow-sonarr-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: sonarr
  ports:
  #Webinterface
  - protocol: TCP
    name: webint
    port: 8989
    targetPort: 8989
---
#Ingress resource. Picked up by the NGINX ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  annotations:
    kubernets.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 85.144.63.138,192.168.1.0/24
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - sonarr.k8s.array21.dev
    secretName: array21-tls
  rules:
  - host: sonarr.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
