apiVersion: v1
kind: PersistentVolume
metadata:
  name: fill-pod
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: catexplorer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fill-pod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: fill-pod
  storageClassName: longhorn-static
---
apiVersion: v1
kind: Pod
metadata:
  name: fill-pod
spec:
  containers:
  - name: fill-pod
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: fill-pod
      
