apiVersion: v1
kind: Secret
metadata:
  name: bookstack-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "Ym9va3N0YWNrCg=="
  node.session.auth.password: "UU5Ga0ZBdXh0QzZCMkN2NDYyNU0K"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-config
spec:
  capacity:
    storage: 25G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.4:3260
    iqn: 'iqn.2021-05.intern.array21.dev:bookstack'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: bookstack-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
spec:
  volumeName: bookstack-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: docker-registry.k8s.array21.dev/bookstack:latest
        env:
        - name: "APP_URL"
          value: "https://wiki.k8s.array21.dev"
        - name: "DB_HOST"
          value: "mariadb.intern.array21.dev"
        - name: "DB_DATABASE"
          value: "bookstack"
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: db-username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: db-password
        volumeMounts:
        - name: bookstack-config
          mountPath: /var/www/bookstack
        ports:
        - name: web
          containerPort: 80
      volumes:
      - name: bookstack-config
        persistentVolumeClaim:
          claimName: bookstack-config
---
apiVersion: v1
kind: Service
metadata:
  name: bookstack
spec:
  type: LoadBalancer
  selector:
    app: bookstack
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstack
  annotations:
    kubernets.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
spec:
  tls:
  - hosts:
    - wiki.k8s.array21.dev
    secretName: array21-tls
  rules:
  - host: wiki.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookstack
            port:
              number: 80
