apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer
  namespace: homelab
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: homer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: homer
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homelab
  labels:
    app.kubernetes.io/name: homer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homer
    spec:
      automountServiceAccountToken: false
      containers:
      - name: homer
        image: b4bz/homer:latest
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: homer
          mountPath: /www/assets
      volumes:
      - name: homer
        persistentVolumeClaim:
          claimName: homer
---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: homelab
spec:
  selector:
    app.kubernetes.io/name: homer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer
  namespace: homelab
  annotations:
    kubernets.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: 'letsencrypt-array21'
spec:
  tls:
  - hosts:
    - homer.k8s.array21.dev
    secretName: homer-k8s-array21-dev
  rules:
  - host: homer.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homer
            port:
              number: 8080
