apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data
  namespace: homelab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: transmission
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission-data
  storageClassName: longhorn-static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: homelab
  name: transmission-download
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/transmission
    server: storage-hdd.intern.array21.dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homelab
  name: transmission-download
spec:
  storageClassName: ""
  volumeName: transmission-download
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: homelab
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: "haugene/transmission-openvpn:3.7"
        ports:
        - containerPort: 9091
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: "OPENVPN_PROVIDER"
          value: "PIA"
        - name: "PIA_OPENVPN_CONFIG_BUNDLE"
          value: "openvpn"
        - name: "OPENVPN_USERNAME"
          valueFrom:
            secretKeyRef:
              name: transmission
              key: pia-username
        - name: "OPENVPN_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: transmission
              key: pia-password
        - name: "OPENVPN_CONFIG"
          value: "spain"
        - name: "CREATE_TUN_DEVICE"
          value: "true"
        - name: "LOCAL_NETWORK"
          value: "10.0.0.0/8,172.16.0.0/12"
        - name: "WEBPROXY_ENABLED"
          value: "false"
        - name: "OPENVPN_OPTS"
          value: "--inactive 3600 --ping 10 --ping-exit 60"
        - name: "TRANSMISSION_WEB_UI"
          value: "flood-for-transmission"
        - name: "TRANSMISSION_INCOMPLETE_DIR_ENABLED"
          value: "false"
        - name: "TRANSMISSION_IDLE_SEEDING_LIMIT"
          value: "100000"
        - name: "TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED"
          value: "false"
        - name: "TRANSMISSION_PEER_LIMIT_GLOBAL"
          value: "500"
        - name: "TRANSMISSION_DOWNLOAD_QUEUE_SIZE"
          value: "100"
        - name: "TRANSMISSION_SEED_QUEUE_SIZE"
          value: "800"
        - name: "TRANSMISSION_SEED_QUEUE_ENABLED"
          value: "true"
        - name: "TRANSMISSION_RATIO_LIMIT_ENABLED"
          value: "true"
        - name: "TRANSMISSION_RATIO_LIMIT"
          value: "2"
        - name: "TRANSMISSION_DHT_ENABLED"
          value: "false"
        - name: "TRANSMISSION_PEX_ENABLED"
          value: "false"
        - name: "TRANSMISSION_PEER_PORT"
          value: "51414"
        - name: "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED"
          value: "false"
        volumeMounts:
        - name: transmission-data
          mountPath: /data/transmission-home
        - name: transmission-download
          mountPath: /data/completed
      volumes:
      - name: transmission-data
        persistentVolumeClaim:
          claimName: transmission-data
      - name: transmission-download
        persistentVolumeClaim:
          claimName: transmission-download
---
apiVersion: v1
kind: Service
metadata:
  namespace: homelab
  name: transmission
spec:
  selector:
    app: transmission
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homelab
  name: transmission
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.10.0.0/16"
    cert-manager.io/cluster-issuer: 'letsencrypt-array21'
spec:
  tls:
  - hosts:
    - transmission.k8s.array21.dev
    secretName: transmission-k8s-array21-dev
  rules:
  - host: transmission.k8s.array21.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission
            port: 
              number: 9091
