apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-controller
  namespace: drone
  labels:
    app: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-controller
  template:
    metadata:
      labels:
        app: drone-controller
    spec:
      serviceAccountName: drone
      containers:
      - name: drone-controller
        image: drone/drone:2.0.4
        env:
        - name: "DRONE_GITHUB_CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: drone
              key: github-client-id
        - name: "DRONE_GITHUB_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: drone
              key: github-client-secret
        - name: "DRONE_RPC_SECRET"
          valueFrom:
            secretKeyRef:
              name: drone
              key: rpc-secret
        - name: "DRONE_SERVER_HOST"
          value: "drone.k8s.array21.dev:10443"
        - name: "DRONE_SERVER_PROTO"
          value: "https"
        - name: "DRONE_TLS_CERT"
          value: "/etc/certs/drone.k8s.array21.dev/tls.crt"
        - name: "DRONE_TLS_KEY"
          value: "/etc/certs/drone.k8s.array21.dev/tls.key"
        - name: "DRONE_USER_CREATE"
          value: "username:tobias,admin:true"
        - name: "DRONE_SERVICE_ACCOUNT_DEFAULT"
          value: "drone"
        - name: "DRONE_DATABASE_DRIVER"
          value: "mysql"
        - name: "DRONE_DATABASE_DATASOURCE"
          valueFrom:
            secretKeyRef:
              name: drone
              key: datatabse
        ports:
        - containerPort: 443
          name: webinterface
        volumeMounts:
        - name: ssl-keys
          mountPath: /etc/certs/drone.k8s.array21.dev/
          readOnly: true
      volumes:
      - name: ssl-keys
        secret:
          secretName: controller-drone-k8s-array21-tls