apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: drone
spec:
  hard:
    requests.ephemeral-storage: 12Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
  namespace: drone
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
      ephemeral-storage: 2Gi
    type: Container
