kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
spec:
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "2"
    staleReplicaTimeout: "2880"
    fromBackup: ""
