apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-twinsight-media
  namespace: cert-manager
spec:
  acme:
    email: t.debruijn@array21.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-twinsight-media
    solvers:
    - dns01:
        cloudflare:
          email: cloudflare@signin.array21.dev
          apiTokenSecretRef:
            name: cloudflare-twinsight-media
            key: api_token
