apiVersion: apps/v1
kind: Deployment
metadata:
  name: authlander
  namespace: mrfriendly
  labels:
    app.kubernetes.io/name: authlander
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authlander
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authlander
    spec:
      automountServiceAccountToken: false
      containers:
      - name: authlander
        image: docker-registry.k8s.array21.dev/authlander:latest
        securityContext:
          capabilities:
            drop:
            - CAP_NET_RAW
        ports:
        - name: api
          containerPort: 8080
        env:
        - name: "GOOGLE_CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: authlander
              key: google-client-id
        - name: "GOOGLE_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: authlander
              key: google-client-secret
        - name: "HOST"
          value: "https://authlander.intern.mrfriendly.nl"
        - name: "MYSQL_HOST"
          value: "10.10.4.4"
        - name: "MYSQL_DATABASE"
          value: "mrfriendly_prod_authlander"
        - name: "MYSQL_USERNAME"
          valueFrom:
            secretKeyRef:
              name: authlander
              key: mysql-username
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: authlander
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: authlander
  namespace: mrfriendly
spec:
  selector:
    app.kubernetes.io/name: authlander
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authlander
  namespace: mrfriendly
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-mrfriendly"
spec:
  tls:
  - hosts:
    - authlander.intern.mrfriendly.nl
    secretName: authlander-intern-mrfriendly-nl
  rules:
  - host: authlander.intern.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authlander
            port:
              number: 8080
