kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mrfriendly
  name: drone-runner
rules:
- apiGroups:
  - apps
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  - ""
  resources:
  - pods
  - pods/log
  - apps
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner
  namespace: mrfriendly
subjects:
- kind: ServiceAccount
  name: drone-runner
  namespace: default
roleRef:
  kind: Role
  name: drone-runner
  apiGroup: rbac.authorization.k8s.io
