apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailsync
  namespace: mrfriendly
  labels:
    app: mailsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailsync
  template:
    metadata:
      labels:
        app: mailsync
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mailsync-api
        image: docker-registry.k8s.array21.dev/mrfriendly-mailsync-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port
        env:
        - name: "DEBUG"
          value: "true"
        - name: "AUTH_API_TOKEN"
          valueFrom:
            secretKeyRef:
              name: mailsync-api
              key: auth_api_token
        - name: "FRONTEND_HOST"
          value: "https://intern.mrfriendly.nl"
        - name: "AUTH_SERVER_HOST"
          value: "https://authlander.intern.mrfriendly.nl"
        - name: "ESPO_HOST"
          value: "https://espocrm.intern.mrfriendly.nl"
        - name: "ESPO_API_KEY"
          valueFrom:
            secretKeyRef:
              name: mailsync-api
              key: espo_api_key
        - name: "ESPO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: mailsync-api
              key: espo_api_secret
        - name: "MYSQL_HOST"
          value: "mariadb.intern.array21.dev"
        - name: "MYSQL_DB"
          value: "mrfriendly_prod_mailsync"
        - name: "MYSQL_USERNAME"
          valueFrom:
            secretKeyRef:
              name: mailsync-api
              key: mysql_username
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mailsync-api
              key: mysql_password
      # TODO Frontend container
---
apiVersion: v1
kind: Service
metadata:
  name: mailsync
  namespace: mrfriendly
spec:
  selector:
    app: mailsync
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
  #TODO Frontend ports
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailsync-api
  namespace: mrfriendly
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-mrfriendly"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - mailsync-api.intern.mrfriendly.nl
    secretName: mailsync-api-intern-mrfriendly-tls
  rules:
  - host: mailsync-api.intern.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailsync
            port:
              number: 8080
      
