apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailsync
  namespace: mrfriendly
  labels:
    app.kubernetes.io/name: mailsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailsync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailsync
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mailsync
        image: docker-registry.k8s.array21.dev/mrfriendly-mailsync:latest
        securityContext:
          capabilities:
            drop:
            - CAP_NET_RAW
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ESPO_API_KEY
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: espo-api-key
        - name: ESPO_API_SECRET
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: espo-api-secret
        - name: ESPO_HOST
          value: "https://espocrm.intern.mrfriendly.nl"
        - name: AUTHLANDER_KEY
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: authlander-key
        - name: AUTHLANDER_HOST
          value: "https://authlander.intern.mrfriendly.nl"
        - name: MYSQL_HOST
          value: "mariadb.intern.array21.dev"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: mysql-database
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailsync
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: mailsync
  namespace: mrfriendly
spec:
  selector:
    app.kubernetes.io/name: mailsync
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailsync-api
  namespace: mrfriendly
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-mrfriendly"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - mailsync.intern.mrfriendly.nl
    secretName: mailsync-intern-mrfriendly-tls
  rules:
  - host: mailsync.intern.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailsync
            port:
              number: 8080