- hosts: all
  become: yes
  tasks:
  # Apt update
  - name: update APT packages
    apt:
      upgrade: yes
      update_cache: yes
  
  # Apt transport HTTPS
  - name: install APT Transport HTTPS
    apt:
      name: apt-transport-https
      state: present

  # Kubernetes APT key
  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  # Kubernetes APT repo
  - name: add Kubernetes' APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  # Dependencies
  - name: Install dependencies for all
    apt:
      name: "{{ item }}" 
      state: present
      update_cache: yes
    loop:
    - kubelet
    - kubeadm
    - containerd
    - nfs-common
    - open-iscsi

  # Load modules
  - name: load modules
    copy:
      content: |
        br_netfilter
      dest: /etc/modules-load.d/k8s.conf
      owner: root
      group: root
      mode: 0640
    register: new_modules

  # Sysctl config
  - name: sysctl configuration
    copy:
      content: |
        #net.bridge.bridge-nf-call-ip6tables = 1         
        net.bridge.bridge-nf-call-iptables = 1          
        net.ipv4.ip_forward = 1                         
        #net.ipv6.conf.all.forwarding = 1                
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: 0640

  - name: reboot
    reboot:
    when: new_modules.changed

  - name: Restart sysctl
    command: /sbin/sysctl -p /etc/sysctl.d/k8s.conf
    failed_when: False

- hosts: master
  become: yes
  tasks:

  # Dependencies
  - name: Install dependencies for master
    apt:
      name: "{{ item }}" 
      state: present
      update_cache: yes
    loop:
    - kubectl
    - acl
    - keepalived