apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterplayer
  labels:
    app: betterplayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betterplayer
  template:
    metadata:
      labels:
        app: betterplayer
    spec:
      containers:
      - name: betterplayer
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/betterplayer:latest
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: betterplayer 
              key: BOT_TOKEN
        - name: "USE_GOOGLE_API"
          value: "true"
        - name: "GOOGLE_API_KEY"
          valueFrom:
            secretKeyRef:
              name: betterplayer
              key: GOOGLE_API_KEY
        - name: "DB_HOST"
          value: "mariadb.intern.array21.dev"
        - name: "DB_NAME"
          value: "betterplayer"
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: betterplayer
              key: DB_USERNAME
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: betterplayer
              key: DB_PASSWORD
        - name: "KSOFT_API_TOKEN"
          valueFrom:
            secretKeyRef:
              name: betterplayer
              key: KSOFT_API_TOKEN
