apiVersion: v1
kind: PersistentVolume
metadata:
  name: catexplorer
  namespace: prodlab
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: catexplorer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catexplorer
  namespace: prodlab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: catexplorer
  storageClassName: longhorn-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catexplorer
  namespace: prodlab
  labels:
    app.kubernetes.io/name: catexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catexplorer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catexplorer
    spec:
      automountServiceAccountToken: false
      containers:
      - name: catexplorer
        image: thedutchmc/catexplorer:latest
        securityContext:
          capabilities:
            drop:
            - CAP_NET_RAW
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: catexplorer
              key: token
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: catexplorer
