apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcm-staging
  namespace: twinsight
  labels:
    app.kubernetes.io/name: tcm-staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tcm-staging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tcm-staging
    spec:
      automountServiceAccountToken: false
      containers:
      - name: tcm-staging
        securityContext:
          capabilities:
            drop:
            - CAP_NET_RAW
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/twinsight-tcm:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: mariadb.intern.array21.dev
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: tcm-staging
              key: mysql-database
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: tcm-staging
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tcm-staging
              key: mysql-password
        - name: PASSWORD_PEPPER
          valueFrom:
            secretKeyRef:
              name: tcm-staging
              key: password-pepper
        - name: DISCORD_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: tcm-staging
              key: discord-webhook
        - name: email_sender
          value: 'noreply@array21.dev'
        - name: frontend_host
          value: 'https://tcm-ui.staging.twinsight.media'
---
apiVersion: v1
kind: Service
metadata:
  name: tcm-staging
  namespace: twinsight
spec:
  selector:
    app.kubernetes.io/name: tcm-staging
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcm-staging
  namespace: twinsight
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-twinsight-media"
spec:
  tls:
  - hosts:
    - tcm.staging.twinsight.media
    secretName: tcm-staging-twinsight-media
  rules:
  - host: tcm.staging.twinsight.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tcm-staging
            port:
              number: 8080
